#!/bin/sh
hdfs dfs -put transitionsmall.txt /transition
hdfs dfs -rm -r /output*
hdfs dfs -rm -r /pagerank*
hdfs dfs -mkdir /pagerank0
hdfs dfs -put prsmall.txt /pagerank0
hadoop jar pr.jar Driver /transition /pagerank /output 5 0.2